language: python
os: linux
env: CIINSTALL=yes

jobs:
  allow_failures:
    - name: xenial-ml
      dist: xenial
      python: 3.7

    - name: bionic-ml
      dist: bionic
      python: 3.7
    
    - name: focal-ml
      dist: focal
      python: 3.7

  include:
    - name: xenial-basic
      dist: xenial
      script:
      - ./1-BasicSetUp.sh
      - export PATH=/opt/anaconda3/bin:$PATH
      - hash -r  # To reload env vars like PATH
      - ./2-GenSoftware.sh
      python: 3.7

    - name: xenial-opencv
      dist: xenial
      script:
      - ./Build-OpenCV.sh
      - ffmpeg -version
      - gdb --ex='set confirm on' -ex=run -ex=bt -ex=quit --args python3 extras/opencv_test.py
      python: 3.7

    - name: xenial-ml
      dist: xenial
      script: ./Build-ML.sh
      python: 3.7

    - name: xenial-ml-basic
      dist: xenial
      script: ./3-ML-Basic.sh
      python: 3.7

    - name: xenial-opencv-conda
      dist: xenial
      script:
      - ./1-BasicSetUp.sh
      - export PATH=/opt/anaconda3/bin:$PATH
      - hash -r  # To reload env vars like PATH
      - ./Build-OpenCV.sh
      - ffmpeg -version
      - gdb --ex='set confirm on' -ex=run -ex=bt -ex=quit --args python extras/opencv_test.py
      python: 3.7

    - name: bionic-basic
      dist: bionic
      script:
      - ./1-BasicSetUp.sh
      - export PATH=/opt/anaconda3/bin:$PATH
      - hash -r  # To reload env vars like PATH
      - ./2-GenSoftware.sh
      python: 3.7

    - name: bionic-opencv
      dist: bionic
      script:
      - ./Build-OpenCV.sh
      - ffmpeg -version
      - gdb --ex='set confirm on' -ex=run -ex=bt -ex=quit --args python3 extras/opencv_test.py
      python: 3.7

    - name: bionic-ml
      dist: bionic
      script: ./Build-ML.sh
      python: 3.7

    - name: bionic-ml-basic
      dist: bionic
      script: ./3-ML-Basic.sh
      python: 3.7

    - name: bionic-opencv-conda
      dist: bionic
      script:
      - ./1-BasicSetUp.sh
      - export PATH=/opt/anaconda3/bin:$PATH
      - hash -r  # To reload env vars like PATH
      - ./Build-OpenCV.sh
      - ffmpeg -version
      - gdb --ex='set confirm on' -ex=run -ex=bt -ex=quit --args python extras/opencv_test.py
      python: 3.7
    
      - name: focal-basic
      dist: focal
      script:
      - ./1-BasicSetUp.sh
      - export PATH=/opt/anaconda3/bin:$PATH
      - hash -r  # To reload env vars like PATH
      - ./2-GenSoftware.sh
      python: 3.7

    - name: focal-opencv
      dist: focal
      script:
      - ./Build-OpenCV.sh
      - ffmpeg -version
      - gdb --ex='set confirm on' -ex=run -ex=bt -ex=quit --args python3 extras/opencv_test.py
      python: 3.7

    - name: focal-ml
      dist: focal
      script: ./Build-ML.sh
      python: 3.7

    - name: focal-ml-basic
      dist: focal
      script: ./3-ML-Basic.sh
      python: 3.7

    - name: focal-opencv-conda
      dist: focal
      script:
      - ./1-BasicSetUp.sh
      - export PATH=/opt/anaconda3/bin:$PATH
      - hash -r  # To reload env vars like PATH
      - ./Build-OpenCV.sh
      - ffmpeg -version
      - gdb --ex='set confirm on' -ex=run -ex=bt -ex=quit --args python extras/opencv_test.py
      python: 3.7

before_install:
    - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) main universe restricted multiverse"
    - sudo apt-get update -qq
    - sudo apt-get install -y software-properties-common
    - sudo apt-get install -qq build-essential curl g++ python3-dev python3-setuptools gdb
    - echo 'America/Los_Angeles' | sudo tee /etc/timezone
    - sudo dpkg-reconfigure --frontend noninteractive tzdata
